project:
  name: VoxelInsight
  description: Medical-imaging assistant for DICOM/NIfTI exploration, AI segmentation and radiomics.

ui:
  name: VoxelInsight
  description: Medical-imaging assistant for DICOM/NIfTI exploration, AI segmentation and radiomics.
  theme: light
  primary_color: "#4F46E5"
  logo: "/static/VoxelInsight.png"
  default_page: "landing"
